### ISSUE TITLE
Issues deploying the boot war module in GlassFish 3.1.2

### ISSUE THREAD

**Issue by ledzepu2** [spring-guides/gs-convert-jar-to-war#12]
I need to deploy an ear module which has an ejb and a war module. we created the war file using spring boot. when i try deploying the ear into glassfish, i get the following log beyond which i dont seem to go beyond..

```
[#|2014-03-04T14:53:51.787+0530|INFO|glassfish3.1.2|javax.enterprise.system.container.web.com.sun.enterprise.web|_ThreadID=17;_ThreadName=Thread-4;|PWC1412: WebModule[null] ServletContext.log():Spring WebApplicationInitializers detected on classpath: [com.espn.api.motorsports.config.WebAppInitializer@18f9ba0]|#]
```

**Comment by fliden** [comment]
Same issue here. Glassfish is complaining about missing Mongo, Solr, ThymeLeaft, etc even though I'm not using them in my project

Class [ com/mongodb/Mongo ] not found. Error while loading [ class org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration ]

Class [ org/apache/solr/client/solrj/SolrServer ] not found. Error while loading [ class org.springframework.boot.autoconfigure.solr.SolrAutoConfiguration ]

lass [ org/thymeleaf/resourceresolver/IResourceResolver ] not found. Error while loading [ class org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration$DefaultTemplateResolverConfiguration ]

**Comment by philwebb** [comment]
There is at least one open issue with glassfish that could account for the "Class Not Found Error" (https://java.net/jira/browse/GLASSFISH-21265). Are you able to try [Payara](http://www.payara.co.uk/downloads), I think that they have applied the patch.

**Comment by DanielMack** [comment]
i just tried it with the latest Payara version (full) - i get the exact same error ... spring boot does not work in WAR mode on a glassfish. At all.
